Repository stackabletech/opa-operator, pull requests merged in 2021-05, with the labels that each got.

#5 Removed hard coded label selector schema and used the one provided in…
  Cargo.lock
  crd/Cargo.toml
  crd/src/lib.rs
  server/Cargo.toml
  server/src/bin/generate_crds.rs
Labels: type/enhancement

#8 Remove redundant release build and introduce caching
  .github/workflows/rust.yml
Labels: priority/low, size/XS, type/enhancement

#9 Added clean command to rust build.
  .github/workflows/rust.yml
Labels: type/enhancement

#18 Add opa reference for other operators
  Cargo.lock
  crd/Cargo.toml
  crd/src/error.rs
  crd/src/lib.rs
  crd/src/util.rs
  examples/simple-opacluster.yaml
  operator/src/error.rs
  operator/src/lib.rs
Labels: size/S, type/enhancement

#21 Fix service path for RHEL
  server/packaging/rpm/SOURCES/stackable-opa-operator-server-VERSION/usr/lib/systemd/system/stackable-opa-operator-server.service
Labels: priority/critical, size/XS, type/bug

#22 Pod names include the node name
  operator/src/lib.rs
Labels: priority/critical, size/S, type/bug

#26 Bring project up to current Stackable best practices
  .github/dependabot.yml
  .github/workflows/build_artifacts.yml
  .github/workflows/rust.yml
  Cargo.lock
  crd/Cargo.toml
  crd/src/lib.rs
  crd/src/util.rs
  deploy/crd/openpolicyagent.crd.yaml
  operator/Cargo.toml
  server/Cargo.toml
  server/packaging/rpm/SPECS/stackable-opa-operator-server.spec
  server/src/bin/generate_crds.rs
  server/src/main.rs
Labels: priority/low, type/enhancement
