Repository stackabletech/opa-operator, pull requests merged in 2021-09, with the labels that each got.

#67 Fixes #58, fixes #57, prepares for release
  Cargo.lock
  crd/Cargo.toml
  deny.toml
  operator/Cargo.toml
  server/Cargo.toml
  server/src/main.rs
Labels: type/enhancement, priority/low

#86 Implemented versioning from operator-rs.
  CHANGELOG.md
  Cargo.lock
  deploy/crd/openpolicyagent.crd.yaml
  rust/crd/Cargo.toml
  rust/crd/src/lib.rs
  rust/operator-binary/Cargo.toml
  rust/operator/Cargo.toml
  rust/operator/src/lib.rs
Labels: type/enhancement, priority/high

#88 Adapted to kube-rs 0.60 and operator-rs 0.2.2.
  CHANGELOG.md
  Cargo.lock
  deploy/crd/openpolicyagent.crd.yaml
  rust/crd/Cargo.toml
  rust/crd/src/lib.rs
  rust/crd/src/util.rs
  rust/operator-binary/Cargo.toml
  rust/operator-binary/src/stackable-opa-operator.rs
  rust/operator/Cargo.toml
  rust/operator/src/lib.rs
Labels: priority/high, type/dependencies
